English:
  ArmorNobleHelmet: Fur hat
  ArmorNobleHelmet_description: Fashionable hat with fur lining
  ArmorNobleChest: Noble's banner garb
  ArmorNobleChest_description: A garb stitched together from banners torn from your burial chamber, a good alternative to roaming Valheim bare
  ArmorNobleLegs: Noble's pants
  ArmorNobleLegs_description: Worn, loose pants from a past life where one could afford to feast more often
  ArmorNobleCape: Vegvisir cape
  ArmorNobleCape_description: Cape fashioned from a vegvisir banner
  ArmorBarbarianBronzeHelmetJD: Barbarian's helmet
  ArmorBarbarianBronzeHelmetJD_description: Helmet made from a bronze alloy
  ArmorBarbarianBronzeChestJD: Barbarian's armor
  ArmorBarbarianBronzeChestJD_description: A bronze disc attached to leather straps, a true barbarian hurls himself into battle despite the lack of protection
  ArmorBarbarianBronzeLegsJD: Barbarian's boots
  ArmorBarbarianBronzeLegsJD_description: Thick hide wrapped around one's waist, fastened with a fashionable bronze belt
  ArmorBarbarianCapeJD: Barbarian's fur cape
  ArmorBarbarianCapeJD_description: Thick, short cape made from fur. Covers ones back when his drunk raidmates can't.
  ArmorWarriorHelmet: Warrior's helmet
  ArmorWarriorHelmet_description: Chainmail wrapping around the neck provides good protection
  ArmorWarriorChest: Warrior's hauberk
  ArmorWarriorChest_description: Long vest made from linked chains
  ArmorWarriorLegs: Warrior's boots
  ArmorWarriorLegs_description: Multi-layered pants keep it's wearer warm and protected
  ArmorPlateIronHelmetJD: Sturdy helmet
  ArmorPlateIronHelmetJD_description: A sturdy helmet with a leather neckguard
  ArmorPlateIronChestJD: Plate mail
  ArmorPlateIronChestJD_description: Thick plates of metal riveted to a leather harness
  ArmorPlateIronLegsJD: Plate greaves
  ArmorPlateIronLegsJD_description: Reliable greaves and kneeguards
  ArmorPlateCape: Boar cape
  ArmorPlateCape_description: Reinforced boar hide worn around one's shoulders like a trophy
  ArmorDragonslayerHelmet: Horned helm
  ArmorDragonslayerHelmet_description: Dragon's tremble in fear when they see the blackened helmet adorned with the horns of their kin
  ArmorDragonslayerChest: Dragonslayer's armor
  ArmorDragonslayerChest_description: Obsidian layer over silver plates makes for reliable protection
  ArmorDragonslayerLegs: Spiked greaves
  ArmorDragonslayerLegs_description: Unlucky is he who finds himself in the way of these
  ArmorWandererHelmet: Straw hat
  ArmorWandererHelmet_description: A reinforced straw hat
  ArmorWandererChest: Coat of plates
  ArmorWandererChest_description: Small metal plates attached to a leather jerkin, easy to maintain during travels
  ArmorWandererLegs: Wanderer's pants
  ArmorWandererLegs_description: Durable pants with makeshift protection around the shins
  ArmorWandererCape: Straw cape
  ArmorWandererCape_description: Cheap to make cape made from straw collected in the plains, protects against the elements but is quick to catch fire
  ArmorBlackmetalgarbHelmet: Nomadic helmet
  ArmorBlackmetalgarbHelmet_description: Blackmetal helmet with colorful padding fit for a nomad
  ArmorBlackmetalgarbChest: Nomadic garb
  ArmorBlackmetalgarbChest_description: A nomadic garb adorned with protective elements made from blackmetal, found commonly in the nomad's homeland, the plains
  ArmorBlackmetalgarbLegs: Nomadic boots
  ArmorBlackmetalgarbLegs_description: Thick leather boots with blackmetal toe guard, helpful when one happens to get stomped on by a Lox
  ArmorSerpentHelmet: Finned helm
  ArmorSerpentHelmet_description: A thick blackmetal casque adorned by the fins of a mighty serpent. The style is popular with raiding knights of the South.
  ArmorSerpentChest: Serpent armor
  ArmorSerpentChest_description: Plates of blackmetal overtop a surcoat of sea serpent scales. The perfect garb for spreading Odin's good word.
  ArmorSerpentLegs: Serpent Cuisses
  ArmorSerpentLegs_description: Blackmetal cuisses, greaves and sabatons. Excellent protection with a slightly fishy smell.
  ArmorSerpentCape: Serpent knight's cape
  ArmorSerpentCape_description: Heavy dark cape of the Serpent order.
  ArmorMistlandsHelmet: Scorched sallet
  ArmorMistlandsHelmet_description: Helmet made from a rare material only found within the ashlands
  ArmorMistlandsChest: Scorched armor
  ArmorMistlandsChest_description: Thick, multi layered gambeson provides protection from the searing heat of flametal, which in turn protects from blows
  ArmorMistlandsLegs: Scorched greaves
  ArmorMistlandsLegs_description: One need not fear the cold while wearing these
  BackpackSimple: Simple backpack
  BackpackSimple_description: Leather container attached to a wooden frame
  BackpackHeavy: Heavy backpack
  BackpackHeavy_description: Large chest hauled on ones shoulders with a canvas bag for additional storage
