PrintComment: Deleting old JTV configs...

DeleteFile:
- config/RecipeCustomizer/AtgeirHeavymetal.json
- config/RecipeCustomizer/AxeHeavymetal.json
- config/RecipeCustomizer/BattleaxeHeavymetal.json
- config/RecipeCustomizer/BowHeavymetal.json
- config/RecipeCustomizer/CursedEffigy.json
- config/RecipeCustomizer/GreatswordHeavymetal.json
- config/RecipeCustomizer/KnifeHeavymetal.json
- config/RecipeCustomizer/MaceHeavymetal.json
- config/RecipeCustomizer/PickaxeHeavymetal.json
- config/RecipeCustomizer/ShieldHeavymetal.json
- config/RecipeCustomizer/ShieldHeavymetalTower.json
- config/RecipeCustomizer/SledgeHeavymetal.json
- config/RecipeCustomizer/SpearHeavymetal.json
- config/RecipeCustomizer/SwordHeavymetal.json
- config/WeaponCustomizer/AtgeirHeavymetal.json
- config/WeaponCustomizer/AxeHeavymetal.json
- config/WeaponCustomizer/BattleaxeHeavymetal.json
- config/WeaponCustomizer/BowHeavymetal.json
- config/WeaponCustomizer/GreatswordHeavymetal.json
- config/WeaponCustomizer/KnifeHeavymetal.json
- config/WeaponCustomizer/MaceHeavymetal.json
- config/WeaponCustomizer/PickaxeHeavymetal.json
- config/WeaponCustomizer/ShieldHeavymetal.json
- config/WeaponCustomizer/SledgeHeavymetal.json
- config/WeaponCustomizer/SpearHeavymetal.json
- config/WeaponCustomizer/SwordHeavymetal.json

