PrintComment: Copying JTV configs...
CopyFile:
- From: plugins/thedefside-Journey_To_Valhalla/DasSauerkraut-Terraheim/balance.json
  To: plugins/DasSauerkraut-Terraheim/balance.json
- From: plugins/thedefside-Journey_To_Valhalla/DasSauerkraut-Terraheim/weaponBalance.json
  To: plugins/DasSauerkraut-Terraheim/weaponBalance.json
- From: plugins/thedefside-Journey_To_Valhalla/DasSauerkraut-Terraheim/english.lang
  To: plugins/DasSauerkraut-Terraheim/english.lang
- From: plugins/thedefside-Journey_To_Valhalla/jtv_configs/ReepusDeepusDelmeepus4902761.ChaosArmor.recipes.json
  To: config/ReepusDeepusDelmeepus4902761.ChaosArmor.recipes.json
DeleteFile:
- config/RecipeCustomizer/BasicWeaponKit_DoD.json
- config/RecipeCustomizer/CrudeWeaponKit_DoD.json
- config/RecipeCustomizer/ExcellentWeaponKit_DoD.json
- config/RecipeCustomizer/ExceptionalWeaponKit_DoD.json
- config/RecipeCustomizer/ExtraordinaryWeaponKit_DoD.json
- config/RecipeCustomizer/FrometalBar.json
- config/RecipeCustomizer/GoodWeaponKit_Dod.json
- config/RecipeCustomizer/GreatWeaponKit_Dod.json
- config/RecipeCustomizer/HeavymeatlBar.json
- config/RecipeCustomizer/SuperiorWeaponKit_Dod.json