PrintComment: Copying JTV configs...
CopyFile:
- From: plugins/thedefside-Journey_To_Valhalla/DasSauerkraut-Terraheim/balance.json
  To: plugins/DasSauerkraut-Terraheim/balance.json
- From: plugins/thedefside-Journey_To_Valhalla/DasSauerkraut-Terraheim/weaponBalance.json
  To: plugins/DasSauerkraut-Terraheim/weaponBalance.json
- From: plugins/thedefside-Journey_To_Valhalla/DasSauerkraut-Terraheim/english.lang
  To: plugins/DasSauerkraut-Terraheim/english.lang
